module.exports = {
  appId: 'io.github.antiranger.lingerlens',
  productName: 'LingerLens',
  directories: { output: 'release' },
  asar: true,
  electronDist: 'build-desktop/electron',
  afterPack: async context => require('./audit-package.cjs').auditPackage(context.appOutDir, context.electronPlatformName),
  // electron-builder normalizes this array in place; keep the audit manifest immutable.
  files: [...require('./audit-package.cjs').APP_FILES],
  extraResources: [
    { from: 'build-desktop/backend/lingerlens-backend', to: 'backend', filter: ['**/*'] },
    { from: 'LICENSE', to: 'LICENSE-LingerLens.txt' },
    { from: 'THIRD_PARTY_NOTICES.md', to: 'THIRD_PARTY_NOTICES.md' },
    { from: 'licenses', to: 'licenses', filter: ['**/*'] },
    { from: 'desktop/DEPENDENCIES.md', to: 'DEPENDENCIES.md' },
  ],
  win: { icon: 'desktop/assets/icon.ico', target: [{ target: 'nsis', arch: ['x64'] }],
    artifactName: 'LingerLens-${version}-windows-${arch}-setup.${ext}' },
  mac: { icon: 'desktop/assets/icon.png', category: 'public.app-category.video',
    target: ['dmg', 'zip'], identity: null,
    artifactName: 'LingerLens-${version}-macos-${arch}.${ext}' },
  nsis: { oneClick: true, perMachine: false, deleteAppDataOnUninstall: false,
    packElevateHelper: false,
    createDesktopShortcut: true, createStartMenuShortcut: true, runAfterFinish: false },
};
